# Generated by Django 3.0.2 on 2020-01-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GPB', 'GPB'), ('RUB', 'RUB'), ('BTC', 'BTC')], default='BTC', max_length=3),
        ),
    ]
