# Generated by Django 3.0.2 on 2020-02-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200131_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='USDRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EUR', models.FloatField(default=0.0)),
                ('GPB', models.FloatField(default=0.0)),
                ('RUB', models.FloatField(default=0.0)),
                ('BTC', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
