# Generated by Django 3.0.2 on 2020-02-04 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usdrelations'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryExchanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GPB', 'GPB'), ('RUB', 'RUB'), ('BTC', 'BTC')], max_length=3)),
                ('transfer_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
