# Generated by Django 3.0.3 on 2020-02-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historyexchanges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usdrelations',
            old_name='GPB',
            new_name='GBP',
        ),
    ]
