# Generated by Django 3.0.3 on 2020-02-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200211_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
