# Generated by Django 3.0.3 on 2020-02-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyexchanges',
            name='target_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
