# Generated by Django 3.0.3 on 2020-02-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historyexchanges_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyexchanges',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historyexchanges',
            name='target_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('RUB', 'RUB'), ('BTC', 'BTC')], max_length=3, null=True),
        ),
    ]
